### ISSUE TITLE
[wgsl-in] Naga complains about unsigned literal in switch statement

### ISSUE THREAD

**Issue by afd** [gfx-rs/naga#1029]
Naga (1f42d4f) rejects this WGSL (which was generated by Tint, via the example from issue #1028):

```
[[stage(fragment)]]
fn main() {
  switch(0u) {
    default: {
      if (false) {
        break;
      }
    }
  }
  return;
}
```

I get this output:

```
$ RUST_BACKTRACE=1 cargo run temp.wgsl blah.spv
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/naga temp.wgsl blah.spv`
Entry point main at Fragment is invalid: 
	The `switch` value [1] is not an integer scalar
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/src/main.rs:272:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/option.rs:388:21
   4: naga::main
             at ./cli/src/main.rs:272:45
   5: core::ops::function::FnOnce::call_once
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/ops/function.rs:227:5
```

**Comment by jimblandy** [comment]
I can confirm this. Thanks for the bug report!

**Comment by jimblandy** [comment]
This is `FunctionError::InvalidSwitchType`, raised in `Validator::validate_block_impl`.
