### ISSUE TITLE
[wgsl-in] Naga does not accept switch statement

### ISSUE THREAD

**Issue by afd** [gfx-rs/naga#1030]
Naga (1f42d4f) rejects this WGSL, which is the same as the example in issue #1029 except that I have changed `0u` to `0`. I decided to open a separate issue as #1029 appears to be to do with unsigned literals not being accepted in switch statements, whereas this issue appears to be in Naga's writer.

```
[[stage(fragment)]]
fn main() {
  switch(0) {
    default: {
      if (false) {
        break;
      }
    }
  }
  return;
}
```

Here is the output I get:

```
$ RUST_BACKTRACE=1 cargo run temp.wgsl blah.spv
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/naga temp.wgsl blah.spv`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/back/spv/writer.rs:2579:88
stack backtrace:
   0: rust_begin_unwind
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/option.rs:388:21
   4: naga::back::spv::writer::<impl naga::back::spv::Writer>::write_block
             at ./src/back/spv/writer.rs:2579:66
   5: naga::back::spv::writer::<impl naga::back::spv::Writer>::write_block
             at ./src/back/spv/writer.rs:2440:25
   6: naga::back::spv::writer::<impl naga::back::spv::Writer>::write_block
             at ./src/back/spv/writer.rs:2514:21
   7: naga::back::spv::writer::<impl naga::back::spv::Writer>::write_function
             at ./src/back/spv/writer.rs:440:9
   8: naga::back::spv::writer::<impl naga::back::spv::Writer>::write_entry_point
             at ./src/back/spv/writer.rs:476:27
   9: naga::back::spv::writer::<impl naga::back::spv::Writer>::write_logical_layout
             at ./src/back/spv/writer.rs:2846:34
  10: naga::back::spv::writer::<impl naga::back::spv::Writer>::write
             at ./src/back/spv/writer.rs:2890:9
  11: naga::back::spv::write_vec
             at ./src/back/spv/mod.rs:305:5
  12: naga::main
             at ./cli/src/main.rs:272:21
  13: core::ops::function::FnOnce::call_once
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/ops/function.rs:227:5
```

**Comment by jimblandy** [comment]
I can confirm this. Thank you for the bug report!

**Comment by jimblandy** [comment]
The SPIR-V back end isn't handing jumps very well. See also #1017.
