### ISSUE TITLE
[wgsl-in] Atomic parsing seems broken.

### ISSUE THREAD

**Issue by dragostis** [gfx-rs/naga#1194]
```wgsl
var<workgroup> x: atomic<u32>;

fn foo() {
    atomicStore(&x, 2);
}
```

fails with ``Option::unwrap() on a `None` value``.

**Comment by kvark** [comment]
@dragostis we actually have atomic tests now in this repo. Could you try making it a struct with atomic fields, just out of curiosity?

**Comment by kvark** [comment]
Also, please attach the stack trace.

**Comment by dragostis** [comment]
Same thing happened with this:

```wgsl
struct Foo {
    x: atomic<u32>;
};

var<workgroup> f: Foo;

fn foo() {
    atomicStore(&f.x, 2);
}
```

Here's a stack trace when running the CLI validator on this:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/front/mod.rs:36:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:388:21
   4: naga::front::Emitter::finish
             at ./src/front/mod.rs:36:25
   5: naga::front::wgsl::ExpressionContext::interrupt_emitter
             at ./src/front/wgsl/mod.rs:821:27
   6: naga::front::wgsl::Parser::parse_primary_expression
             at ./src/front/wgsl/mod.rs:1907:17
   7: naga::front::wgsl::Parser::parse_singular_expression
             at ./src/front/wgsl/mod.rs:2119:30
   8: naga::front::wgsl::Parser::parse_equality_expression::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/front/wgsl/mod.rs:2194:49
   9: naga::front::wgsl::ExpressionContext::parse_binary_splat_op
             at ./src/front/wgsl/mod.rs:777:24
  10: naga::front::wgsl::Parser::parse_equality_expression::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/front/wgsl/mod.rs:2179:41
  11: naga::front::wgsl::ExpressionContext::parse_binary_splat_op
             at ./src/front/wgsl/mod.rs:777:24
  12: naga::front::wgsl::Parser::parse_equality_expression::{{closure}}::{{closure}}::{{closure}}
             at ./src/front/wgsl/mod.rs:2168:33
  13: naga::front::wgsl::ExpressionContext::parse_binary_op
             at ./src/front/wgsl/mod.rs:754:24
  14: naga::front::wgsl::Parser::parse_equality_expression::{{closure}}::{{closure}}
             at ./src/front/wgsl/mod.rs:2155:25
  15: naga::front::wgsl::ExpressionContext::parse_binary_op
             at ./src/front/wgsl/mod.rs:754:24
  16: naga::front::wgsl::Parser::parse_equality_expression::{{closure}}
             at ./src/front/wgsl/mod.rs:2144:17
  17: naga::front::wgsl::ExpressionContext::parse_binary_op
             at ./src/front/wgsl/mod.rs:754:24
  18: naga::front::wgsl::Parser::parse_equality_expression
             at ./src/front/wgsl/mod.rs:2135:9
  19: naga::front::wgsl::Parser::parse_general_expression::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/front/wgsl/mod.rs:2257:49
  20: naga::front::wgsl::ExpressionContext::parse_binary_op
             at ./src/front/wgsl/mod.rs:754:24
  21: naga::front::wgsl::Parser::parse_general_expression::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/front/wgsl/mod.rs:2248:41
  22: naga::front::wgsl::ExpressionContext::parse_binary_op
             at ./src/front/wgsl/mod.rs:754:24
  23: naga::front::wgsl::Parser::parse_general_expression::{{closure}}::{{closure}}::{{closure}}
             at ./src/front/wgsl/mod.rs:2238:33
  24: naga::front::wgsl::ExpressionContext::parse_binary_op
             at ./src/front/wgsl/mod.rs:754:24
  25: naga::front::wgsl::Parser::parse_general_expression::{{closure}}::{{closure}}
             at ./src/front/wgsl/mod.rs:2230:25
  26: naga::front::wgsl::ExpressionContext::parse_binary_op
             at ./src/front/wgsl/mod.rs:754:24
  27: naga::front::wgsl::Parser::parse_general_expression::{{closure}}
             at ./src/front/wgsl/mod.rs:2222:17
  28: naga::front::wgsl::ExpressionContext::parse_binary_op
             at ./src/front/wgsl/mod.rs:754:24
  29: naga::front::wgsl::Parser::parse_general_expression
             at ./src/front/wgsl/mod.rs:2214:22
  30: naga::front::wgsl::Parser::parse_statement
             at ./src/front/wgsl/mod.rs:3291:29
  31: naga::front::wgsl::Parser::parse_block
             at ./src/front/wgsl/mod.rs:3360:13
  32: naga::front::wgsl::Parser::parse_function_decl
             at ./src/front/wgsl/mod.rs:3472:20
  33: naga::front::wgsl::Parser::parse_global_decl
             at ./src/front/wgsl/mod.rs:3693:21
  34: naga::front::wgsl::Parser::parse
             at ./src/front/wgsl/mod.rs:3729:19
  35: naga::front::wgsl::parse_str
             at ./src/front/wgsl/mod.rs:3746:5
  36: naga::run
             at ./cli/src/main.rs:215:26
  37: naga::main
             at ./cli/src/main.rs:154:21
  38: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
```
