### ISSUE TITLE
Shader compilation errors on Metal (macos 10.13.6)

### ISSUE THREAD

**Issue by daviewales** [gfx-rs/naga#1339]
I'm trying to run [Veloren](https://veloren.net/) on Mac, and I'm getting the following naga errors:

```
❯ RUST_BACKTRACE=full ./airshipper
[WARN] Naga generated shader:
// language: metal2.0
#include <metal_stdlib>
#include <simd/simd.h>

struct Globals {
    metal::float4x4 transform;
};
struct VertexInput {
    metal::float2 v_pos;
    metal::float2 pos;
    metal::float2 scale;
    metal::float2 atlas_pos;
    metal::float2 atlas_scale;
    int layer;
};
struct VertexOutput {
    metal::float4 position;
    metal::float2 uv;
    float layer;
};

struct vs_mainInput {
    metal::float2 v_pos [[attribute(0)]];
    metal::float2 pos [[attribute(1)]];
    metal::float2 scale [[attribute(2)]];
    metal::float2 atlas_pos [[attribute(3)]];
    metal::float2 atlas_scale [[attribute(4)]];
    int layer [[attribute(5)]];
};
struct vs_mainOutput {
    metal::float4 position [[position]];
    metal::float2 uv [[user(loc0), center_perspective]];
    float layer [[user(loc1), center_perspective]];
};
vertex vs_mainOutput vs_main(
  vs_mainInput varyings [[stage_in]]
, constant Globals& globals [[buffer(0)]]
) {
    const VertexInput input = { varyings.v_pos, varyings.pos, varyings.scale, varyings.atlas_pos, varyings.atlas_scale, varyings.layer };
    VertexOutput out;
    metal::float4x4 transform;
    out.uv = static_cast<float2>((input.v_pos * input.atlas_scale) + input.atlas_pos);
    out.layer = static_cast<float>(input.layer);
    transform = metal::float4x4(metal::float4(input.scale.x, 0.0, 0.0, 0.0), metal::float4(0.0, input.scale.y, 0.0, 0.0), metal::float4(0.0, 0.0, 1.0, 0.0), metal::float4(input.pos, 0.0, 1.0));
    metal::float4x4 _e40 = globals.transform;
    metal::float4x4 _e41 = transform;
    out.position = (_e40 * _e41) * metal::float4(input.v_pos, 0.0, 1.0);
    VertexOutput _e48 = out;
    const auto _tmp = _e48;
    return vs_mainOutput { _tmp.position, _tmp.uv, _tmp.layer };
}


struct fs_mainInput {
    metal::float2 uv [[user(loc0), center_perspective]];
    float layer [[user(loc1), center_perspective]];
};
struct fs_mainOutput {
    metal::float4 member1 [[color(0)]];
};
fragment fs_mainOutput fs_main(
  fs_mainInput varyings1 [[stage_in]]
, metal::float4 position [[position]]
, metal::sampler u_sampler [[sampler(0)]]
, metal::texture2d_array<float, metal::access::sample> u_texture [[texture(0)]]
) {
    const VertexOutput input1 = { position, varyings1.uv, varyings1.layer };
    metal::float4 _e7 = u_texture.sample(u_sampler, input1.uv, static_cast<int>(input1.layer));
    return fs_mainOutput { _e7 };
}

[WARN] Shader translation error for stage VERTEX: Metal: Compilation failed:

program_source:42:26: error: unknown type name 'float2'; did you mean 'float'?
    out.uv = static_cast<float2>((input.v_pos * input.atlas_scale) + input.atlas_pos);
                         ^~~~~~
                         float
program_source:42:14: error: static_cast from 'metal::float2' (aka 'vector_float2') to 'float' is not allowed
    out.uv = static_cast<float2>((input.v_pos * input.atlas_scale) + input.atlas_pos);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[WARN] Please report it to https://github.com/gfx-rs/naga
[ERROR] wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `iced_wgpu::image pipeline`
    Internal error in VERTEX shader: Metal: Compilation failed:

program_source:42:26: error: unknown type name 'float2'; did you mean 'float'?
    out.uv = static_cast<float2>((input.v_pos * input.atlas_scale) + input.atlas_pos);
                         ^~~~~~
                         float
program_source:42:14: error: static_cast from 'metal::float2' (aka 'vector_float2') to 'float' is not allowed
    out.uv = static_cast<float2>((input.v_pos * input.atlas_scale) + input.atlas_pos);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



[ERROR] Airshipper panicked:

Handling wgpu errors as fatal by default: panicked at 'Handling wgpu errors as fatal by default', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/backend/direct.rs:2159:5
thread 'main' panicked at 'Handling wgpu errors as fatal by default', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/backend/direct.rs:2159:5
stack backtrace:
   0:        0x10681b7f2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8e4ba4b55e218172
   1:        0x1064ed63c - core::fmt::write::h678ac65252cdb936
   2:        0x106819b0a - std::io::Write::write_fmt::h6e4183435968e8c5
   3:        0x10681aa57 - std::panicking::default_hook::{{closure}}::h2d4327b072954705
   4:        0x106819ea9 - std::panicking::default_hook::hf452eeb666b7d536
   5:        0x106428759 - airshipper::error::panic_hook::{{closure}}::h4a2dd3a01392fef2
   6:        0x1068199fe - std::panicking::rust_panic_with_hook::hde5e2d5c940e2374
   7:        0x1068a626d - std::panicking::begin_panic::{{closure}}::hc5aa8631e6df413a
   8:        0x1068a6238 - std::sys_common::backtrace::__rust_end_short_backtrace::hb08e1bb139842c60
   9:        0x1069ac3bd - std::panicking::begin_panic::hc1881e98836881de
  10:        0x1068b0bc4 - wgpu::backend::direct::default_error_handler::h329ce89e2898eebe
  11:        0x1068b0a10 - core::ops::function::Fn::call::h019d29cd931cd9d4
  12:        0x1068c8374 - wgpu::Device::create_render_pipeline::h2c1b2a6aa17fdc59
  13:        0x106596728 - iced_wgpu::backend::Backend::new::hbebfe5b87e416756
  14:        0x10645714a - airshipper::gui::run::h18e0829aef36590d
  15:        0x10641bb46 - airshipper::cli::process::hb418343c5d05897f
  16:        0x1063b0c36 - airshipper::main::h5ef89ad357ef1e7c
  17:        0x1063ee92a - std::sys_common::backtrace::__rust_begin_short_backtrace::hfa8db7b546750383
  18:        0x1063b15c4 - _main
zsh: abort      RUST_BACKTRACE=full ./airshipper
```

**Comment by kvark** [comment]
Thank you for the bug report! What naga version is this?

**Comment by daviewales** [comment]
That was quick! Thank you!
