### ISSUE TITLE
[hlsl-out] fma function should use mad for single-precision floats

### ISSUE THREAD

**Issue by parasyte** [gfx-rs/naga#1579]
It looks like HLSL has two different functions for "Fused Multiply-Add":

- [`fma`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-fma)
- [`mad`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/mad)

They differ only in precision, with `fma` accepting `double` and `mad ` accepting `float`. Naga converts the WGSL `fma` function into HLSL `fma` regardless of the input types, which leads to a D3D compile error when the shader is used by `wgpu`.

```wgsl
// fma.wgsl
struct VertexOutput {
    [[location(0)]] tex_coord: vec2<f32>;
};

[[stage(vertex)]]
fn vs_main(
    [[location(0)]] position: vec2<f32>,
) -> VertexOutput {
    var out: VertexOutput;
    out.tex_coord = fma(position, vec2<f32>(0.5, -0.5), vec2<f32>(0.5, 0.5));
    return out;
}
```

Convert to HLSL with `naga-cli`:

```
$ cargo run -- fma.wgsl fma.hlsl --validate 31
$ cat fma.hlsl
```

```hlsl
struct VertexOutput {
    linear float2 tex_coord : LOC0;
};

struct VertexOutput_vs_main {
    float2 tex_coord : LOC0;
};

VertexOutput_vs_main vs_main(float2 position : LOC0)
{
    VertexOutput out_ = (VertexOutput)0;

    out_.tex_coord = fma(position, float2(0.5, -0.5), float2(0.5, 0.5));
    VertexOutput _expr10 = out_;
    const VertexOutput vertexoutput = _expr10;
    const VertexOutput_vs_main vertexoutput_1 = { vertexoutput.tex_coord };
    return vertexoutput_1;
}
```

When `wgpu` compiles this shader with the DX12 backend, we get an error like this:

```
[2021-12-07T13:18:59Z WARN  wgpu::backend::direct] Shader translation error for stage VERTEX: D3DCompile error (0x80004005): C:\Users\jay\projects\shaders\scale.wgsl(34,22-71): error X3013: 'fma': no matching 3 parameter intrinsic function
    C:\Users\jay\projects\shaders\scale.wgsl(34,22-71): error X3013: Possible intrinsic functions are:
    C:\Users\jay\projects\shaders\scale.wgsl(34,22-71): error X3013:     fma(double, double, double)

[2021-12-07T13:18:59Z WARN  wgpu::backend::direct] Please report it to https://github.com/gfx-rs/naga
[2021-12-07T13:18:59Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error
```

<details><summary>Additional details</summary>

The full end-to-end situation where this bug is hit is in [`pixels`](https://github.com/parasyte/pixels). Repro by cloning the repo and running the `minimal-winit` example on Windows with the DirectX 12 backend:

```
$ WGPU_BACKEND=dx12 RUST_LOG=info RUST_BACKTRACE=1 cargo run --package minimal-winit
```

The full log is:

```
[2021-12-07T13:18:59Z INFO  wgpu_core::instance] Adapter Dx12 AdapterInfo { name: "NVIDIA GeForce RTX 3090", vendor: 4318, device: 8708, device_type: DiscreteGpu, backend: Dx12 }
[2021-12-07T13:18:59Z INFO  wgpu_core::device] Created texture Valid((0, 1, Dx12)) with TextureDescriptor { label: Some("pixels_source_texture"), size: Extent3d { width: 320, height: 240, depth_or_array_layers: 1 }, mip_level_count: 1, sample_count: 1, dimension: D2, format: Rgba8UnormSrgb, usage: COPY_DST | TEXTURE_BINDING }
[2021-12-07T13:18:59Z INFO  wgpu_core::device] Created buffer Valid((0, 1, Dx12)) with BufferDescriptor { label: Some("pixels_scaling_renderer_vertex_buffer"), size: 24, usage: VERTEX, mapped_at_creation: true }
[2021-12-07T13:18:59Z INFO  wgpu_core::device] Created buffer Valid((1, 1, Dx12)) with BufferDescriptor { label: Some("pixels_scaling_renderer_matrix_uniform_buffer"), size: 64, usage: COPY_DST | UNIFORM, mapped_at_creation: true }
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::device] Naga generated shader for "vs_main" at Vertex:
    struct NagaConstants {
        int base_vertex;
        int base_instance;
        uint other;
    };
    ConstantBuffer<NagaConstants> _NagaConstants: register(b1);

    struct VertexOutput {
        linear float2 tex_coord : LOC0;
        float4 position : SV_Position;
    };

    struct Locals {
        row_major float4x4 transform;
    };

    cbuffer r_locals : register(b0) { Locals r_locals; }
    Texture2D<float4> r_tex_color : register(t0);
    SamplerState r_tex_sampler : register(s0);

    struct VertexOutput_vs_main {
        float2 tex_coord_1 : LOC0;
        float4 position_1 : SV_Position;
    };

    struct FragmentInput_fs_main {
        float2 tex_coord_2 : LOC0;
    };

    VertexOutput_vs_main vs_main(float2 position : LOC0)
    {
        VertexOutput out_ = (VertexOutput)0;

        out_.tex_coord = fma(position, float2(0.5, -0.5), float2(0.5, 0.5));
        float4x4 _expr13 = r_locals.transform;
        out_.position = mul(float4(position, 0.0, 1.0), _expr13);
        VertexOutput _expr18 = out_;
        const VertexOutput vertexoutput = _expr18;
        const VertexOutput_vs_main vertexoutput_1 = { vertexoutput.tex_coord, vertexoutput.position };
        return vertexoutput_1;
    }

    float4 fs_main(FragmentInput_fs_main fragmentinput_fs_main) : SV_Target0
    {
        float2 tex_coord = fragmentinput_fs_main.tex_coord_2;
        float4 _expr4 = r_tex_color.Sample(r_tex_sampler, tex_coord);
        return _expr4;
    }

[2021-12-07T13:18:59Z WARN  wgpu::backend::direct] Shader translation error for stage VERTEX: D3DCompile error (0x80004005): C:\Users\jay\projects\shaders\scale.wgsl(34,22-71): error X3013: 'fma': no matching 3 parameter intrinsic function
    C:\Users\jay\projects\shaders\scale.wgsl(34,22-71): error X3013: Possible intrinsic functions are:
    C:\Users\jay\projects\shaders\scale.wgsl(34,22-71): error X3013:     fma(double, double, double)

[2021-12-07T13:18:59Z WARN  wgpu::backend::direct] Please report it to https://github.com/gfx-rs/naga
[2021-12-07T13:18:59Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pixels_scaling_renderer_pipeline`
    Internal error in VERTEX shader: D3DCompile error (0x80004005): C:\Users\jay\projects\shaders\scale.wgsl(34,22-71): error X3013: 'fma': no matching 3 parameter intrinsic function
C:\Users\jay\projects\shaders\scale.wgsl(34,22-71): error X3013: Possible intrinsic functions are:
C:\Users\jay\projects\shaders\scale.wgsl(34,22-71): error X3013:     fma(double, double, double)


', C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:2195:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\core\src\panicking.rs:107
   2: wgpu::backend::direct::default_error_handler
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:2195
   3: core::ops::function::Fn::call<void (*)(enum$<wgpu::Error>),tuple$<enum$<wgpu::Error> > >
             at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\library\core\src\ops\function.rs:70
   4: alloc::boxed::impl$46::call<tuple$<enum$<wgpu::Error> >,dyn$<wgpu::UncapturedErrorHandler,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\library\alloc\src\boxed.rs:1744
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:2183
   6: wgpu::backend::direct::Context::handle_error<enum$<wgpu_core::pipeline::CreateRenderPipelineError> >
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:184
   7: wgpu::backend::direct::impl$3::device_create_render_pipeline
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:1276
   8: wgpu::Device::create_render_pipeline
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\lib.rs:1770
   9: pixels::renderers::ScalingRenderer::new
             at .\src\renderers.rs:142
  10: pixels::builder::create_backing_texture
             at .\src\builder.rs:397
  11: pixels::builder::impl$0::build_impl::generator$0<winit::window::Window>
             at .\src\builder.rs:269
  12: core::future::from_generator::impl$1::poll<pixels::builder::impl$0::build_impl::generator$0>
             at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\library\core\src\future\mod.rs:80
  13: pollster::block_on<core::future::from_generator::GenFuture<pixels::builder::impl$0::build_impl::generator$0> >
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\pollster-0.2.4\src\lib.rs:132
  14: pixels::builder::PixelsBuilder<winit::window::Window>::build<winit::window::Window>
             at .\src\builder.rs:320
  15: pixels::Pixels::new<winit::window::Window>
             at .\src\lib.rs:202
  16: minimal_winit::main
             at .\examples\minimal-winit\src\main.rs:41
  17: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,enum$<pixels::Error> >, 0, 4, Err> (*)(),tuple$<> >
             at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-12-07T13:18:59Z INFO  wgpu_core::hub] Dropping Global
[2021-12-07T13:18:59Z INFO  wgpu_core::device] Destroying 0 command encoders
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance] Process is terminating. Using simple reporting. Please call ReportLiveObjects() at runtime for standard reporting.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance] Live Producer at 0x0000015B8164CC90, Refcount: 1.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81813B50, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81824DE0, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81848AB0, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B818457F0, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81846D50, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81846A90, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B818138F0, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81856AE0, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B819B88A0, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance] Live                         Object :      9
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance] Live Producer at 0x0000015B819F7AE0, Refcount: 1.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81A27D40, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81A22890, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81A44880, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81A8BF20, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81A8C690, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81A3EDF0, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81A91060, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81A912C0, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000015B81AA9670, Refcount: 0.
[2021-12-07T13:18:59Z WARN  wgpu_hal::dx12::instance] Live                         Object :      9
error: process didn't exit successfully: `target\debug\minimal-winit.exe` (exit code: 101)
```
</details>

It is interesting to note that the shader path given in the error message is incorrect. But that's a `wgpu` bug.

**Comment by parasyte** [comment]
I trivially patched the HLSL writer to use `mad` and it does indeed work. This is _not_ the right way to fix this, but proves the concept.

```diff
diff --git a/src/back/hlsl/writer.rs b/src/back/hlsl/writer.rs
index ce51a48..288a3f9 100644
--- a/src/back/hlsl/writer.rs
+++ b/src/back/hlsl/writer.rs
@@ -1869,7 +1869,7 @@ impl<'a, W: fmt::Write> super::Writer<'a, W> {
                     Mf::Refract => Function::Regular("refract"),
                     // computational
                     Mf::Sign => Function::Regular("sign"),
-                    Mf::Fma => Function::Regular("fma"),
+                    Mf::Fma => Function::Regular("mad"),
                     Mf::Mix => Function::Regular("lerp"),
                     Mf::Step => Function::Regular("step"),
                     Mf::SmoothStep => Function::Regular("smoothstep"),
```

<details><summary>Full run log for <code>minimal-winit</code></summary>

```
[2021-12-07T13:55:55Z INFO  wgpu_core::instance] Adapter Dx12 AdapterInfo { name: "NVIDIA GeForce RTX 3090", vendor: 4318, device: 8708, device_type: DiscreteGpu, backend: Dx12 }
[2021-12-07T13:55:55Z INFO  wgpu_core::device] Created texture Valid((0, 1, Dx12)) with TextureDescriptor { label: Some("pixels_source_texture"), size: Extent3d { width: 320, height: 240, depth_or_array_layers: 1 }, mip_level_count: 1, sample_count: 1, dimension: D2, format: Rgba8UnormSrgb, usage: COPY_DST | TEXTURE_BINDING }
[2021-12-07T13:55:55Z INFO  wgpu_core::device] Created buffer Valid((0, 1, Dx12)) with BufferDescriptor { label: Some("pixels_scaling_renderer_vertex_buffer"), size: 24, usage: VERTEX, mapped_at_creation: true }
[2021-12-07T13:55:55Z INFO  wgpu_core::device] Created buffer Valid((1, 1, Dx12)) with BufferDescriptor { label: Some("pixels_scaling_renderer_matrix_uniform_buffer"), size: 64, usage: COPY_DST | UNIFORM, mapped_at_creation: true }
[2021-12-07T13:55:55Z INFO  wgpu_hal::dx12::device] Naga generated shader for "vs_main" at Vertex:
    struct NagaConstants {
        int base_vertex;
        int base_instance;
        uint other;
    };
    ConstantBuffer<NagaConstants> _NagaConstants: register(b1);

    struct VertexOutput {
        linear float2 tex_coord : LOC0;
        float4 position : SV_Position;
    };

    struct Locals {
        row_major float4x4 transform;
    };

    cbuffer r_locals : register(b0) { Locals r_locals; }
    Texture2D<float4> r_tex_color : register(t0);
    SamplerState r_tex_sampler : register(s0);

    struct VertexOutput_vs_main {
        float2 tex_coord_1 : LOC0;
        float4 position_1 : SV_Position;
    };

    struct FragmentInput_fs_main {
        float2 tex_coord_2 : LOC0;
    };

    VertexOutput_vs_main vs_main(float2 position : LOC0)
    {
        VertexOutput out_ = (VertexOutput)0;

        out_.tex_coord = mad(position, float2(0.5, -0.5), float2(0.5, 0.5));
        float4x4 _expr13 = r_locals.transform;
        out_.position = mul(float4(position, 0.0, 1.0), _expr13);
        VertexOutput _expr18 = out_;
        const VertexOutput vertexoutput = _expr18;
        const VertexOutput_vs_main vertexoutput_1 = { vertexoutput.tex_coord, vertexoutput.position };
        return vertexoutput_1;
    }

    float4 fs_main(FragmentInput_fs_main fragmentinput_fs_main) : SV_Target0
    {
        float2 tex_coord = fragmentinput_fs_main.tex_coord_2;
        float4 _expr4 = r_tex_color.Sample(r_tex_sampler, tex_coord);
        return _expr4;
    }

[2021-12-07T13:55:55Z INFO  wgpu_hal::dx12::device] Naga generated shader for "fs_main" at Fragment:
    struct NagaConstants {
        int base_vertex;
        int base_instance;
        uint other;
    };
    ConstantBuffer<NagaConstants> _NagaConstants: register(b1);

    struct VertexOutput {
        linear float2 tex_coord : LOC0;
        float4 position : SV_Position;
    };

    struct Locals {
        row_major float4x4 transform;
    };

    cbuffer r_locals : register(b0) { Locals r_locals; }
    Texture2D<float4> r_tex_color : register(t0);
    SamplerState r_tex_sampler : register(s0);

    struct VertexOutput_vs_main {
        float2 tex_coord_1 : LOC0;
        float4 position_1 : SV_Position;
    };

    struct FragmentInput_fs_main {
        float2 tex_coord_2 : LOC0;
    };

    VertexOutput_vs_main vs_main(float2 position : LOC0)
    {
        VertexOutput out_ = (VertexOutput)0;

        out_.tex_coord = mad(position, float2(0.5, -0.5), float2(0.5, 0.5));
        float4x4 _expr13 = r_locals.transform;
        out_.position = mul(float4(position, 0.0, 1.0), _expr13);
        VertexOutput _expr18 = out_;
        const VertexOutput vertexoutput = _expr18;
        const VertexOutput_vs_main vertexoutput_1 = { vertexoutput.tex_coord, vertexoutput.position };
        return vertexoutput_1;
    }

    float4 fs_main(FragmentInput_fs_main fragmentinput_fs_main) : SV_Target0
    {
        float2 tex_coord = fragmentinput_fs_main.tex_coord_2;
        float4 _expr4 = r_tex_color.Sample(r_tex_sampler, tex_coord);
        return _expr4;
    }

[2021-12-07T13:55:55Z INFO  wgpu_core::device] configuring surface with SurfaceConfiguration { usage: RENDER_ATTACHMENT, format: Bgra8UnormSrgb, width: 320, height: 240, present_mode: Fifo }
[2021-12-07T13:55:57Z INFO  wgpu_core::device] Buffer (0, 1, Dx12) is dropped
[2021-12-07T13:55:57Z INFO  wgpu_core::device] Buffer (1, 1, Dx12) is dropped
[2021-12-07T13:55:57Z INFO  wgpu_core::hub] Dropping Global
[2021-12-07T13:55:57Z INFO  wgpu_hal::dx12::device] Waiting for idle with value 1
[2021-12-07T13:55:57Z INFO  wgpu_core::device] Destroying 3 command encoders
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance] Process is terminating. Using simple reporting. Please call ReportLiveObjects() at runtime for standard reporting.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance] Live Producer at 0x000001801701D420, Refcount: 1.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180170D9C30, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180171D3B80, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180171F7810, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180171F4730, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180171F5230, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180171EC070, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000018016DD8060, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000018016DD8A60, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000018017365FA0, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance] Live                         Object :      9
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance] Live Producer at 0x00000180173A8630, Refcount: 1.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180173D7820, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180173D5250, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180173F54D0, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000018017440E70, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180174415E0, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180173F7BB0, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180173F7E70, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x0000018017445E00, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance]   Live Object at 0x00000180174662F0, Refcount: 0.
[2021-12-07T13:55:57Z WARN  wgpu_hal::dx12::instance] Live                         Object :      9
```
</details>

**Comment by kvark** [comment]
Thank you! Wouldn't applying your patch be the right way to go right now? Until we support `double`, that is.

**Comment by parasyte** [comment]
Is there no support for `f64` yet? In that case, by all means, I'll create a PR right now. 😅

**Comment by kvark** [comment]
Right. I think supporting `f64` is not going to be too complicated, since the code largely doesn't assume a specific bit width, but we don't have right now.
