### ISSUE TITLE
[spirv-out] panic on writing output for simple Rosetta test

### ISSUE THREAD

**Issue by pjoe** [gfx-rs/naga#175]
I'm getting a panic when trying to use spirv-out for the [simple Rosetta test](https://github.com/gfx-rs/naga/blob/master/test-data/simple/simple.wgsl):

```
$ RUST_BACKTRACE=1 cargo run --all-features --example convert test-data/simp
le/simple.wgsl target/out.spv true                                                                         
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s                                              
     Running `target/debug/examples/convert test-data/simple/simple.wgsl target/out.spv true`              
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/back/spv/writer.rs:62:40      
stack backtrace:                                                                                           
   0: backtrace::backtrace::libunwind::trace                                                               
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs
:86                                                                                                        
   1: backtrace::backtrace::trace_unsynchronized                                                           
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66   
   2: std::sys_common::backtrace::_print_fmt                                                               
             at src/libstd/sys_common/backtrace.rs:78                                                      
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt                    
             at src/libstd/sys_common/backtrace.rs:59                                                      
   4: core::fmt::write                                                                                     
             at src/libcore/fmt/mod.rs:1076                                                                
   5: std::io::Write::write_fmt                                                                            
             at src/libstd/io/mod.rs:1537                                                                  
   6: std::sys_common::backtrace::_print                                                                   
             at src/libstd/sys_common/backtrace.rs:62                                                      
   7: std::sys_common::backtrace::print                                                                    
             at src/libstd/sys_common/backtrace.rs:49                                                      
   8: std::panicking::default_hook::{{closure}}                                                            
             at src/libstd/panicking.rs:198                                                                
   9: std::panicking::default_hook                                                                         
             at src/libstd/panicking.rs:217                                                                
  10: std::panicking::rust_panic_with_hook                                                                 
             at src/libstd/panicking.rs:526                                                                
  11: rust_begin_unwind                                                                                    
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:50
  14: core::option::Option<T>::unwrap
             at /home/code/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:10
  15: naga::back::spv::writer::Function::to_words
             at src/back/spv/writer.rs:62
  16: naga::back::spv::writer::Writer::write_logical_layout
             at src/back/spv/writer.rs:1547
  17: naga::back::spv::writer::Writer::write
             at src/back/spv/writer.rs:1575
  18: convert::main
             at examples/convert.rs:191
  19: std::rt::lang_start::{{closure}}
             at /home/code/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  22: std::panicking::try
             at src/libstd/panicking.rs:325
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: std::rt::lang_start
             at /home/code/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Napokue** [comment]
Thank you for the issue! I tested it, and found out that this is an issue **not** at the SPIR-V back-end, but rather at the front-end and/or IR. 

SPIR-V always requires a termination at the end of a block. So in this case it is a void return, which is simply just `return` at the end of a function. However, for now you need to explicitly specify the `return` in the function.

A long term fix would be for the IR to check if a function has an explicit return, if not implicitly add it.

**Comment by kvark** [comment]
The check should be a part of #59, but it's not there yet

**Comment by pjoe** [comment]
Ok, so should we add explicit `return` in the Rosetta test until this is fixed?

FYI: I added `return` support for glsl-new in #179

**Comment by Napokue** [comment]
I say for now that would be the best thing to do, as the validation pass is not yet implemented. But first we need #179 for that, then it would be trivial to add the explicit `return`.

**Comment by kristoff3r** [comment]
I don't know spirv well at all, but why can't we just do something like

```
block
    .termination
    .as_ref()
    .unwrap_or(&super::instructions::instruction_return())
    .to_words(sink);
```

Is it just to benefit the other backends as well that it needs to be a validator pass, or should it sometimes do something else than a simple return?

**Comment by Napokue** [comment]
Yes that is possible, but the point is that it should never reach a back-end whenever a terminate isn't present. So there will probably be two options as far as I can think of now:
1) We check it at the validator pass and throw an compiler error.
2) We add a check to the optimization pass and "magically" add a return, when the source code does not contain it.

**Comment by kvark** [comment]
The IR has to have a non-valued `return` regardless of what we do here. So we might as well require this at IR level that all control flow paths from a function end up in this `return`. I suppose the changes to frontends would be fairly trivial?

**Comment by pjoe** [comment]
Sounds simple enough, will try adding to glsl-in
