### ISSUE TITLE
[spv-out] unwrap called on a None value

### ISSUE THREAD

**Issue by JCapucho** [gfx-rs/naga#234]
Backtrace:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:1031:48
stack backtrace:
   // Cut
   4: <naga::back::spv::writer::Writer>::write_expression::{closure#0}
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:1031
   5: <core::slice::iter::Iter<naga::back::spv::writer::LocalVariable> as core::iter::traits::iterator::Iterator>::find::<<naga::back::spv::writer::Writer>::write_expression::{closure#0}>
             at /home/capucho/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:251
   6: <naga::back::spv::writer::Writer>::write_expression
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:1028
   7: <naga::back::spv::writer::Writer>::write_block
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:1246
   8: <naga::back::spv::writer::Writer>::write_function
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:324
   9: <naga::back::spv::writer::Writer>::write_entry_point
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:341
  10: <naga::back::spv::writer::Writer>::write_logical_layout
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:1337
  11: <naga::back::spv::writer::Writer>::write
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:1364
   // Cut
```

**Comment by Napokue** [comment]
Thanks for the issue, can you please add your input code, or an equivalent of it to produce this issue consistently.

**Comment by JCapucho** [comment]
Sorry forgot to add it, I was able to reduce it to this and still trigger the unwrap
```rust
(
    header: (
        version: (1, 0, 0),
        generator: 0,
    ),
    types: [
        (
            name: None,
            inner: Vector(
                size: Tri,
                kind: Float,
                width: 4,
            ),
        )
    ],
    constants: [],
    global_variables: [
        (
            name: Some("a_position"),
            class: Input,
            binding: Some(Location(0)),
            ty: 1,
            interpolation: None,
            storage_access: (
                bits: 0,
            ),
        )
    ],
    functions: [],
    entry_points: {
        (Vertex, "main"): (
            early_depth_test: None,
            workgroup_size: (0, 0, 0),
            function: (
                name: None,
                parameter_types: [],
                return_type: None,
                global_usage: [
                    (
                        bits: 1,
                    ),
                ],
                local_variables: [
                    (
                        name: None,
                        ty: 1,
                        init: None,
                    ),
                ],
                expressions: [
                    LocalVariable(1),
                    GlobalVariable(1),
                ],
                body: [
                    Store(
                        pointer: 1,
                        value: 2,
                    ),
                ],
            ),
        ),
    },
)
```

**Comment by Napokue** [comment]
I see, the reason it crashes is because the defined local variable doesn't have a name. How did you manage to create a local variable without a name?

**Comment by JCapucho** [comment]
I'm working on a little language and using Naga as the backend and it seems like in one of the optimisations steps a new variable was created to store a temporary value and as such the name was set to None

**Comment by Napokue** [comment]
I'm not sure if that is valid at the moment, I haven't looked into all front-ends, but none of them don't do that as far as I know. Maybe @kvark can shed some more light on this, and determine if this is something back-ends have to check or if this never can happen in the back-end and has to be fixed in IR.

**Comment by Napokue** [comment]
Yes I was afraid that would be the case. I assumed "Expression::LocalVariable" always had a set `Name`, cause that was the only reference I could get to be completely certain we found the right local variable. 

We need to look at this closer when we pick this up and strategize about how to tackle this.

**Comment by JCapucho** [comment]
This seems to be fixed. Running a simple glsl shader trough glslang while stripping the debug symbols produces a spirv binary which when parsed has no name for the local variable. Converting this spirv to spirv doesn't seem to trigger the panic.

<details>
  <summary>Glsl shader</summary>

```glsl
#version 460

void main() {
	float a = 0.0;
}
```
</details>

<details>
  <summary>Spirv disassembly</summary>

```
        OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %4 "main"
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
%_ptr_Function_float = OpTypePointer Function %float
    %float_0 = OpConstant %float 0
          %4 = OpFunction %void None %3
          %5 = OpLabel
          %8 = OpVariable %_ptr_Function_float Function
               OpStore %8 %float_0
               OpReturn
               OpFunctionEnd
```
</details>

<details>
  <summary>IR</summary>

```rust
Module {
    types: {
        [1]: Type {
            name: None,
            inner: Scalar {
                kind: Float,
                width: 4,
            },
        },
        [2]: Type {
            name: None,
            inner: Pointer {
                base: [1],
                class: Function,
            },
        },
    },
    constants: {
        [1]: Constant {
            name: None,
            specialization: None,
            inner: Scalar {
                width: 4,
                value: Sint(
                    0,
                ),
            },
        },
        [2]: Constant {
            name: None,
            specialization: None,
            inner: Scalar {
                width: 4,
                value: Sint(
                    1,
                ),
            },
        },
        [3]: Constant {
            name: None,
            specialization: None,
            inner: Scalar {
                width: 4,
                value: Sint(
                    2,
                ),
            },
        },
        [4]: Constant {
            name: None,
            specialization: None,
            inner: Scalar {
                width: 4,
                value: Sint(
                    3,
                ),
            },
        },
        [5]: Constant {
            name: None,
            specialization: None,
            inner: Scalar {
                width: 4,
                value: Float(
                    0.0,
                ),
            },
        },
    },
    global_variables: {},
    functions: {
        [1]: Function {
            name: None,
            arguments: [],
            result: None,
            local_variables: {
                [1]: LocalVariable {
                    name: None,
                    ty: [1],
                    init: None,
                },
            },
            expressions: {
                [1]: Constant(
                    [1],
                ),
                [2]: Constant(
                    [2],
                ),
                [3]: Constant(
                    [3],
                ),
                [4]: Constant(
                    [4],
                ),
                [5]: Constant(
                    [5],
                ),
                [6]: LocalVariable(
                    [1],
                ),
            },
            named_expressions: {},
            body: Block {
                body: [
                    Store {
                        pointer: [6],
                        value: [5],
                    },
                    Return {
                        value: None,
                    },
                ],
            },
        },
    },
    entry_points: [
        EntryPoint {
            name: "main",
            stage: Vertex,
            early_depth_test: None,
            workgroup_size: [
                0,
                0,
                0,
            ],
            function: Function {
                name: Some(
                    "main_wrap",
                ),
                arguments: [],
                result: None,
                local_variables: {},
                expressions: {},
                named_expressions: {},
                body: Block {
                    body: [
                        Call {
                            function: [1],
                            arguments: [],
                            result: None,
                        },
                    ],
                },
            },
        },
    ],
}
```
</details>
