### ISSUE TITLE
[spv-out] entered unreachable code on Expression::Compose with a struct

### ISSUE THREAD

**Issue by JCapucho** [gfx-rs/naga#235]
Backtrace:
```
thread 'main' panicked at 'internal error: entered unreachable code', /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:868:26
stack backtrace:
   // Cut
   1: <naga::back::spv::writer::Writer>::write_expression
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:868
   2: <naga::back::spv::writer::Writer>::write_block
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:1209
   3: <naga::back::spv::writer::Writer>::write_function
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:324
   4: <naga::back::spv::writer::Writer>::write_logical_layout
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:1332
   5: <naga::back::spv::writer::Writer>::write
             at /home/capucho/.cargo/git/checkouts/naga-dbb2b19faed49210/2b268c9/src/back/spv/writer.rs:1364
   // Cut
```
Relevant spirv documentation:
https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpCompositeConstruct
https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#CompositeType
https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Aggregate

**Comment by Napokue** [comment]
Added this to the SPIR-V back-end checklist, see #13

**Comment by JCapucho** [comment]
This seem to be fixed. Tested with a glsl shader converting to spirv

<details>
  <summary>Glsl shader</summary>

```glsl
#version 460

struct Test {
	float a;
};

void main() {
	Test a = { 0.0 };
}
```
</details>

<details>
  <summary>IR</summary>

```rust
Module {
    types: {
        [1]: Type {
            name: None,
            inner: Scalar {
                kind: Float,
                width: 4,
            },
        },
        [2]: Type {
            name: Some(
                "Test",
            ),
            inner: Struct {
                top_level: false,
                members: [
                    StructMember {
                        name: Some(
                            "a",
                        ),
                        ty: [1],
                        binding: None,
                        offset: 0,
                    },
                ],
                span: 4,
            },
        },
    },
    constants: {
        [1]: Constant {
            name: None,
            specialization: None,
            inner: Scalar {
                width: 4,
                value: Float(
                    0.0,
                ),
            },
        },
        [2]: Constant {
            name: None,
            specialization: None,
            inner: Composite {
                ty: [2],
                components: [
                    [1],
                ],
            },
        },
    },
    global_variables: {},
    functions: {
        [1]: Function {
            name: Some(
                "main",
            ),
            arguments: [],
            result: None,
            local_variables: {
                [1]: LocalVariable {
                    name: Some(
                        "a",
                    ),
                    ty: [2],
                    init: Some(
                        [2],
                    ),
                },
            },
            expressions: {
                [1]: Constant(
                    [1],
                ),
                [2]: Compose {
                    ty: [2],
                    components: [
                        [1],
                    ],
                },
                [3]: LocalVariable(
                    [1],
                ),
            },
            named_expressions: {},
            body: Block {
                body: [
                    Emit(
                        [2..2],
                    ),
                ],
            },
        },
    },
    entry_points: [
        EntryPoint {
            name: "main",
            stage: Vertex,
            early_depth_test: None,
            workgroup_size: [
                0,
                0,
                0,
            ],
            function: Function {
                name: None,
                arguments: [],
                result: None,
                local_variables: {},
                expressions: {},
                named_expressions: {},
                body: Block {
                    body: [
                        Call {
                            function: [1],
                            arguments: [],
                            result: None,
                        },
                        Return {
                            value: None,
                        },
                    ],
                },
            },
        },
    ],
}
```
</details>

<details>
  <summary>Output Spir-v</summary>

```spirv
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %15 "main"
               OpSource GLSL 450
               OpName %Test "Test"
               OpMemberName %Test 0 "a"
               OpName %a "a"
               OpName %main "main"
               OpMemberDecorate %Test 0 Offset 0
       %void = OpTypeVoid
      %float = OpTypeFloat 32
    %float_0 = OpConstant %float 0
       %Test = OpTypeStruct %float
          %6 = OpConstantComposite %Test %float_0
%_ptr_Function_Test = OpTypePointer Function %Test
         %11 = OpTypeFunction %void
       %main = OpFunction %void None %11
          %9 = OpLabel
          %a = OpVariable %_ptr_Function_Test Function %6
               OpBranch %12
         %12 = OpLabel
         %13 = OpCompositeConstruct %Test %float_0
               OpReturn
               OpFunctionEnd
         %15 = OpFunction %void None %11
         %14 = OpLabel
               OpBranch %16
         %16 = OpLabel
         %17 = OpFunctionCall %void %main
               OpReturn
               OpFunctionEnd
```
</details>
