### ISSUE TITLE
[glsl-in] index out of bounds panic

### ISSUE THREAD

**Issue by Herschel** [gfx-rs/naga#800]
The following shader panics with `index out of bounds: the len is 0 but the index is 0` in `ResolveContext::resolve`:

[color.vert.zip](https://github.com/gfx-rs/naga/files/6396497/color.vert.zip)

```
#version 450

// Set 0: globals
layout(set = 0, binding = 0) uniform Globals {
    mat4 view_matrix;
};

// Push constants: matrix + color
layout(push_constant) uniform VertexPushConstants {
    mat4 world_matrix;
};

layout(location = 0) in vec2 position;
layout(location = 1) in vec4 color;

layout(location = 0) out vec4 frag_color;

void main() {
    frag_color = color;
    gl_Position = view_matrix * world_matrix * vec4(position, 0.0, 1.0);
    gl_Position.z = (gl_Position.z + gl_Position.w) / 2.0;
}
```

```
cargo run --features glsl-in,spv-out -- color.vert color.out.vert.spv

    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target\debug\naga.exe color.vert color.out.vert.spv`
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:370] &raw = "450"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:375] integer_radix = 10
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:376] &raw = "450"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:370] &raw = "0"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:375] integer_radix = 10
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:376] &raw = "0"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:370] &raw = "0"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:375] integer_radix = 10
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:376] &raw = "0"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:370] &raw = "0"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:375] integer_radix = 10
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:376] &raw = "0"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:370] &raw = "1"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:375] integer_radix = 10
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:376] &raw = "1"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:370] &raw = "0"
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:375] integer_radix = 10
[C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pp-rs-0.1.0\src\lexer.rs:376] &raw = "0"
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src\proc\typifier.rs:310:40
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
   2: core::panicking::panic_bounds_check
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:69
   3: naga::proc::typifier::ResolveContext::resolve<closure-0>
             at .\src\proc\typifier.rs:310
   4: naga::front::Typifier::grow
             at .\src\front\mod.rs:81
   5: naga::front::glsl::ast::Program::resolve_type
             at .\src\front\glsl\ast.rs:119
   6: naga::front::glsl::ast::Program::field_selection
             at .\src\front\glsl\variables.rs:135
   7: naga::front::glsl::parser::parser::yy_reduce
             at .\src\front\glsl\parser.rs:257
   8: naga::front::glsl::parser::parser::yy_parse_token_2
             at C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pomelo-0.1.5\src\lib.rs:968
   9: naga::front::glsl::parser::parser::yy_parse_token
             at C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pomelo-0.1.5\src\lib.rs:968
  10: naga::front::glsl::parser::parser::Parser::parse
             at C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\pomelo-0.1.5\src\lib.rs:968
  11: naga::front::glsl::parse_str
             at .\src\front\glsl\mod.rs:34
  12: naga::main
             at .\bin\naga.rs:131
  13: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\Michael Welsh\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\naga.exe color.vert color.out.vert.spv` (exit code: 101)
```

naga @ 93e57ff

**Comment by kvark** [comment]
GLSL is pretty much broken atm

**Comment by JCapucho** [comment]
The panic no longer happens the only remaining issue with this shader is #901
